#!/bin/bash
# This script bundles the parent directory into a tarball, and copies it to a
# SCP server for Jenkins to use when running tests. This way, Jenkins won't
# inflate our download numbers by downloading the release off GitHub for every
# test.
set -e

keyPath=$1
tarOut=${TRAVIS_TAG}.tar.gz
base=$(basename $PWD)

cd ..
# Don't include the node_modules directories in the tarball to avoid pinning
# the source code of the dependencies.
tar --exclude='*/node_modules' --exclude='*/node_modules/*' -czf ${tarOut} ${base}
cd ${base}

scp -i ${keyPath} -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ../${tarOut} releaser@jenkins.kelda.io:releases/
rm ../${tarOut}
